import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import BackToTop from "@/components/BackToTop";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "南京邮电大学开源软件镜像站",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="min-h-full">
      <body className="font-sans flex flex-col min-h-[100vh]">
        <Header />
        <div className="pt-[92px] flex-1">{children}</div>
        <BackToTop />
        <Footer />
      </body>
    </html>
  );
}
