import { Box, Download } from "lucide-react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "南京邮电大学开源软件镜像站",
  description: "Generated by create next app",
};

const DownloadsLayout = ({
  children,
  aside,
}: Readonly<{
  children: React.ReactNode;
  aside: React.ReactNode;
}>) => {
  return (
    <main className="w-full">
      <div className="mx-auto max-w-7xl p-6 w-full">
        <div className="text-lg font-bold flex gap-1 items-center pb-4">
          <Download /> 软件下载
        </div>
        <div className="grid grid-cols-8">
          {aside}
          {children}
        </div>
      </div>
    </main>
  );
};
export default DownloadsLayout;
